# Your personal GitHub token
github_token: <your-personal-github-token>
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Domain
domain: <your-wildcard-domain-name-without-asterisk>

# Database
database: <your-main-database-name>
database_test: <your-test-database-name>

# Admin User Information
email: <your-admin-email-id>
username: <your-admin-username>
password: <your-admin-password> #do not enter special char
role: <your-admin-role> #if name of role is not admin please make changes to the config file in yii2

# Guest OS timezone
timezone: Europe/London

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: <your-admin-role>  #unique machine name

# Virtual machine IP
ip: 192.168.83.137

# Virtual machine CPU cores number
cpus: 2

# Virtual machine RAM
memory: 4096
